### ISSUE TITLE
Vpool stuck in extending state

### ISSUE THREAD

**Issue by kszysiu94** [openvstorage/home#41] opened 2016-11-07 10:41 UTC
Hello

I have vpool stuck in "extending" state. I made it 2 times in a row.

1.Created vpool with storage router A
2.Added storage router B
3. Removed storage router A
4. Added storage router A with different "storage IP"
5. storage pool stuck in "extending" (blue dot) for long time. Nothing helps. I can't add/remove storage routers from vpool.

**Comment by wimpers** [comment] 2016-11-07 13:35
@JeffreyDevloo , @kinvaris  can you try to reproduce with an autotest please?

**Comment by kinvaris** [comment] 2016-11-08 11:17
The tests of yesterday and today succeeded with no errors of this kind. Is it possible to have a look on this environment @kszysiu94 ?

**Comment by kszysiu94** [comment] 2016-11-08 11:22
No way:( Its internal network without internet access for security reasons (just repos via proxy):(
Is there something i can give you? Some logs etc?

**Comment by JeffreyDevloo** [comment] 2016-11-08 13:24
Our automated tests have indeed passed. 
However your use case is something different than what we test.

I will setup an environment and repeat your steps to see if I can reproduce the issue and gave you some more insight.

**Comment by kinvaris** [comment] 2016-11-08 13:26
@kszysiu94, no problem. You can give us all the logs of ovs-workers (of all nodes), ovs-webapps (of all nodes) & the logs of the ovs-volumedriver-<vpool_name> on the node that the extend failed.

**Comment by JeffreyDevloo** [comment] 2016-11-08 15:08
### Information
I have failed to reproduce this issue on the latest environment. (see testing below)
My assumption is that there was an error during the vpool extending that was properly caught. To debug further, I will require the logs that Kinvaris proposed.

### Steps
- Configured cluster (disk roles, backend, disks and asds)
- Added vpool 'myvpool01' on storagerouter '10.100.199.151' with storage_ip '10.100.199.151'
- Extended vpool 'myvpool01' to storagerouter '10.100.199.152' with storage_ip '10.100.199.152'
- Removed vpool 'myvpool01' on storagerouter '10.100.199.151' (the storage_ip was '10.100.199.151')
- Extended vpool 'myvpool01' on storagerouter '10.100.199.151' with storage_ip '172.22.199.151'

#### Code wise (using our internal setup code)

```
# Copyright (C) 2016 iNuron NV
#
# This file is part of Open vStorage Open Source Edition (OSE),
# as available from
#
#      http://www.openvstorage.org and
#      http://www.openvstorage.com.
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License v3 (GNU AGPLv3)
# as published by the Free Software Foundation, in version 3 as it comes
# in the LICENSE.txt file of the Open vStorage OSE distribution.
#
# Open vStorage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY of any kind.

from ci.helpers.api import OVSClient
from ci.setup.vpool import VPoolSetup
from ci.remove.vpool import VPoolRemover


class VPoolTester(object):
    api = OVSClient('10.100.199.151', 'admin', 'admin')
    nodes = {
        "node1": {"guid": "0773a2bb-93fe-4a3d-b4ab-ccdd356ef2d4",
                  "ip": ["10.100.199.151", "172.22.199.151"]
                  },
        "node2": {"guid": "75219e4b-05b0-4608-a97a-275d7f3d364e",
                  "ip": ["10.100.199.152", "172.22.199.152"]
                  },
        "node3": {"guid": "6ced823f-c12d-47e1-ab23-e64c0c32b6f6",
                  "ip": ["10.100.199.153", "172.22.199.153"]
                  }
    }
    vpool_name = "myvpool01"
    backend_name = "mybackend01"

    @staticmethod
    def run():
        VPoolTester.start_test()

    @staticmethod
    def start_test():
        # Flow : create on A, extend to B, remove A, add A with different IP
        vpool_details = {
            "backend_name": VPoolTester.backend_name,
            "preset": "default",
            "storage_ip": "10.100.199.151",
            "fragment_cache": {
              "strategy": {"cache_on_read":True, "cache_on_write":True},
              "location": "disk"
            },
            "storagedriver": {
              "sco_size": 4,
              "cluster_size": 4,
              "volume_write_buffer": 512,
              "global_write_buffer": 7,
              "dtl_transport": "tcp",
              "dtl_mode": "a_sync"
            }
          }
        vpool_details2 = vpool_details.copy()
        vpool_details2["storage_ip"] = "10.100.199.152"

        vpool_details3 = vpool_details.copy()
        vpool_details3["storage_ip"] = "172.22.199.151"

        VPoolSetup.add_vpool(vpool_name=VPoolTester.vpool_name, vpool_details=vpool_details, api=VPoolTester.api, storagerouter_ip="10.100.199.151", albabackend_name=VPoolTester.backend_name)
        # Extend vpool to B
        VPoolSetup.add_vpool(vpool_name=VPoolTester.vpool_name, vpool_details=vpool_details2, api=VPoolTester.api, storagerouter_ip="10.100.199.152", albabackend_name=VPoolTester.backend_name)
        # Remove vpool on node A
        VPoolRemover.remove_vpool(vpool_name=VPoolTester.vpool_name, storagerouter_ip="10.100.199.151", api=VPoolTester.api)
        # Extend to node A with different IP - should get stuck here according to https://github.com/openvstorage/home/issues/41
        VPoolSetup.add_vpool(vpool_name=VPoolTester.vpool_name, vpool_details=vpool_details3, api=VPoolTester.api, storagerouter_ip="10.100.199.151", albabackend_name=VPoolTester.backend_name)

if __name__ == "__main__":
    VPoolTester().run()


```
### Output
![selection_053](https://cloud.githubusercontent.com/assets/17570109/20104085/ea4db634-a5cc-11e6-8c64-953d3511b5c5.png)
![selection_054](https://cloud.githubusercontent.com/assets/17570109/20104086/ec16bbbe-a5cc-11e6-9ea3-ea5d8372c812.png)
![selection_055](https://cloud.githubusercontent.com/assets/17570109/20104087/ed812d86-a5cc-11e6-9709-8f8afca802e1.png)

#### Code wise
```
2016-11-08 15:56:21 05100 +0100 - ovs-node-1 - 3817/140225128756992 - setup/ci_vpool_setup - 0 - INFO - Creation of vPool `myvpool01` should have succeeded on storagerouter `10.100.199.151`
2016-11-08 15:56:47 28300 +0100 - ovs-node-1 - 3817/140225128756992 - setup/ci_vpool_setup - 1 - INFO - Creation of vPool `myvpool01` should have succeeded on storagerouter `10.100.199.152`
2016-11-08 15:57:11 35600 +0100 - ovs-node-1 - 3817/140225128756992 - remove/ci_vpool_remover - 2 - INFO - Deleting vPool `myvpool01` on storagerouter `10.100.199.151` should have succeeded
2016-11-08 15:57:32 35800 +0100 - ovs-node-1 - 3817/140225128756992 - setup/ci_vpool_setup - 3 - INFO - Creation of vPool `myvpool01` should have succeeded on storagerouter `10.100.199.151`
```
### Packages
```
- openvstorage                         2.7.5-rev.4281.6612d8c-1        amd64        openvStorage
- openvstorage-backend                 1.7.5-rev.811.c1b83e6-1         amd64        openvStorage Backend plugin
- openvstorage-backend-core            1.7.5-rev.811.c1b83e6-1         amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps         1.7.5-rev.811.c1b83e6-1         amd64        openvStorage Backend plugin Web Applications
- openvstorage-core                    2.7.5-rev.4281.6612d8c-1        amd64        openvStorage core
- openvstorage-hc                      1.7.5-rev.811.c1b83e6-1         amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                     1.6.5-rev.423.713f250-1         amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps                 2.7.5-rev.4281.6612d8c-1        amd64        openvStorage Web Applications

```

**Comment by kszysiu94** [comment] 2016-11-10 12:53
os: ubuntu 14.04.03 (i was trying on 14.04.5, but there is kernel 4++ and blktap do not build)
ovs: stable, installed using "quick guide" on every node

packages:
`dpkg -l | grep openvstorage
ii  blktap-openvstorage-utils           2.0.90-2ubuntu3                                          amd64        utilities to work with VHD disk images files
ii  libblktapctl0-openvstorage          2.0.90-2ubuntu3                                          amd64        Xen API blktapctl shared library (shared library)
ii  libvhd0-openvstorage                2.0.90-2ubuntu3                                          amd64        VHD file format access library
ii  libvhdio-2.0.90-openvstorage        2.0.90-2ubuntu3                                          amd64        Xen API blktap shared library (shared library)
ii  openvstorage                        2.7.3-fargo.1-1                                          amd64        openvStorage
ii  openvstorage-backend                1.7.3-fargo.1-1                                          amd64        openvStorage Backend plugin
ii  openvstorage-backend-core           1.7.3-fargo.1-1                                          amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps        1.7.3-fargo.1-1                                          amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-cinder-plugin          1.2.2-fargo.1-1                                          amd64        OpenvStorage Cinder plugin for OpenStack
ii  openvstorage-core                   2.7.3-fargo.1-1                                          amd64        openvStorage core
ii  openvstorage-hc                     1.7.3-fargo.1-1                                          amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-sdm                    1.6.3-fargo.1-1                                          amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                2.7.3-fargo.1-1                                          amd64        openvStorage Web Applications
`


Cluster is running for few days now, i created second vpool and it works, but there were 5 zip log files. So i took the oldest and uploaded here:
http://sprunge.us/YTLF

**Comment by JeffreyDevloo** [comment] 2016-11-10 14:33
Thanks, I will investigate the issue.

**Comment by wimpers** [comment] 2016-11-22 10:27
@kszysiu94 any update on this ticket?

**Comment by wimpers** [comment] 2016-11-30 14:38
Closed as we can't reproduce and didn't receive the necessary logs. Please re-open if you can reproduce the issue or if you have the logs available.

**Closed** 2016-11-30 14:37 UTC
Labels: state_question
